server:
  port: 7003
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        #  使用 githu 外部配置
        git:
          uri: https://gitee.com/wait_for_you_to_love_me/my-blog-config.git #github路径
          search-paths:
            - my-blog-config    # 配置文件的文件名
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
